@url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTVhMzE1Yjg4OTBjMDM0MDg3ZDdmYmUiLCJyb2xlIjoidXNlciIsIm5hbWUiOiJBU0RGIiwiZXhwIjoxNTg4MTUzMTc5LjU4NywiaWF0IjoxNTgyOTY5MTc5fQ.LxgVn5frk2L0ZOMuSG9TNJqQ3FNMO30DAKq211X0AVo
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTNkMTE4MDM5ZGFmODAwMDQ3YTQyOWUiLCJyb2xlIjoiYWRtaW4iLCJuYW1lIjoiYWRtaW4iLCJleHAiOjE1ODgxNDY3NDQuOTI4LCJpYXQiOjE1ODI5NjI3NDR9.AygNJLHJTHX9FEPEUyxgn8ykjMAoXldkR8ZdOvFFFYs
###
# API 
###
POST {{url}}/api/auth/signup
Content-Type: application/json

{
    "name": "ASDF",
    "email": "asdfasdf@mail",
    "password": "asfdasdf",
    "rollNumber" : "asdf",
    "hostelName": "asf",
    "roomNumber": "asdf"
}

###
POST {{url}}/api/auth/signin
Content-Type: application/json

{
    "email": "reach2anandu@gmail.com",
    "password": "password"
}


###

POST {{url}}/api/auth/signin
Content-Type: application/json

{
    "email": "f_hostel@nitc.ac.in",
    "password": "f_hostel@nitc.ac.in"
}

###
GET {{url}}/api/users/me
Authorization: Bearer {{token}}

###
GET {{url}}/api/users/dues
Authorization: Bearer {{token}}

### 
POST {{url}}/api/dues/add
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "rollNumber": "B180288CS",
    "message": "EXTRA", 
    "amount": 1,
    "date": 1581523219956
}

###
POST {{url}}/api/dues/messcut
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "start": 0,
    "end": 1581523219956,
    "rollNumber": "B180283CS"
}
###
DELETE {{url}}/api/dues/delete
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "_id": "5e2af5997e17082947798dd6"
}

###
GET {{url}}/api/dues/list
Authorization: Bearer {{adminToken}}
Content-Type: application/json


###
POST {{url}}/api/admin/assign-mess
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "rollNumber": "B180283CS",
    "mess": "F"
}

###
POST {{url}}/api/admin/student/dues
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "rollNumber": "B160094CS"
}

###

GET {{url}}/api/admin/list-people
Authorization: Bearer {{adminToken}}
###
GET {{url}}/api/admin/list-people-without-mess
Authorization: Bearer {{adminToken}}

###
DELETE {{url}}/api/admin/remove-from-mess
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "rollNumber": "B180288CS"
}
