@url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTJhZjUzODA3ZjRlYjI4ZWI1YTlhYTMiLCJyb2xlIjoiYWRtaW4iLCJuYW1lIjoiYW5hbmR1IiwiZXhwIjoxNTg1MTE4MDMzLjU0OSwiaWF0IjoxNTc5OTM0MDMzfQ.ssuZf2smk8QeBXgQBVSi4AWYWclIbGwgqK3LuaezV4s
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTJhZjUzODA3ZjRlYjI4ZWI1YTlhYTMiLCJyb2xlIjoiYWRtaW4iLCJuYW1lIjoiYW5hbmR1IiwiZXhwIjoxNTg1MTE3OTk4LjUzMywiaWF0IjoxNTc5OTMzOTk4fQ.wyJmhfx2hue_yEOf80OV6URHzdIU1hRkiBvXIiJaMCg
###
# API 
###
POST {{url}}/api/auth/signup
Content-Type: application/json

{
    "name": "anandu",
    "email": "reach2anandu+2@gmail.com",
    "password": "password",
    "rollNumber" : "B180388cs"
}

###
POST {{url}}/api/auth/signin
Content-Type: application/json

{
    "email": "admin@anandu.net",
    "password": "password"
}


###

POST {{url}}/api/auth/signin
Content-Type: application/json

{
    "email": "reach2anandu@gmail.com",
    "password": "password"
}

###
GET {{url}}/api/users/me
Authorization: Bearer {{token}}

###
GET {{url}}/api/users/dues
Authorization: Bearer {{token}}

### 
POST {{url}}/api/dues/add
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "rollNumber": "b180288Cs",
    "message": "Juice", 
    "amount": 80
}
###
DELETE {{url}}/api/dues/delete
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "_id": "5e2af5997e17082947798dd6"
}

###
GET {{url}}/api/dues/list
Authorization: Bearer {{adminToken}}
Content-Type: application/json


###
POST {{url}}/api/admin/assign-mess
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "rollNumber": "B180288CS",
    "mess": "P2"
}

###
GET {{url}}/api/admin/list-people-without-mess
Authorization: Bearer {{adminToken}}

###
DELETE {{url}}/api/admin/remove-from-mess
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "rollNumber": "B180288CS"
}
